import os
import pandas as pd
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from tqdm import tqdm

# ====================
# GLOBAL CONFIGURATION
# ====================
# This is the CSV generated by scrape_img_urls.py
IMG_URLS_DEST = "production_image_extraction_list.csv"

# The root directory where folders will be created
BASE_STORAGE_DIRECTORY = "downloaded_plant_images" #I don't have a good name for this, any suggestions?

# Threading Configuration (Java FixedThreadPool size)
MAX_CONCURRENT_DOWNLDRS = 25
REQUEST_TIMEOUT_SECS = 15

def create_target_directory(species_name: str) -> Path:
    """
    Creates a sanitized folder for each species.
    Note: Filenames contain spaces
    """
    sanitized_folder_name = species_name.replace("/", "-").replace("\\", "-")
    target_path = Path(BASE_STORAGE_DIRECTORY) / sanitized_folder_name
    target_path.mkdir(parents=True, exist_ok=True)
    return target_path

def execute_image_download(url: str, save_path: Path) -> bool:
    """
    Performs the IO operation.
    Includes RESUME LOGIC: skips if the file already exists.
    """
    # RESUME LOGIC: Check disk before hitting network
    if save_path.exists():
        return True

    try:
        # Ensuring we use 'medium' size as requested to save storage
        optimized_url = url.replace("/original/", "/medium/").replace("/large/", "/medium/")

        network_response = requests.get(optimized_url, timeout=REQUEST_TIMEOUT_SECS)
        network_response.raise_for_status()

        with open(save_path, 'wb') as local_file:
            local_file.write(network_response.content)
        return True
    except Exception as error:
        # Log failure but keep the thread pool running
        return False

def run_production_downloader():
    """
    The main execution engine.
    Parallel download of ~2 million images.
    """
    if not os.path.exists(IMG_URLS_DEST):
        print(f"CRITICAL ERROR: {IMG_URLS_DEST} not found.")
        return

    # Load the 'Image URL List'
    extraction_df = pd.read_csv(IMG_URLS_DEST)
    print(f"Beginning parallel download for {len(extraction_df)} entries...")

    # ThreadPoolExecutor is essentially a Java FixedThreadPool for Python
    with ThreadPoolExecutor(max_workers=MAX_CONCURRENT_DOWNLDRS) as executor:
        task_map = {}

        for index, row in extraction_df.iterrows():
            folder = create_target_directory(row['scientific_name'])
            # Creating a unique filename for the specific entry
            file_destination = folder / f"img_{index}.jpg"

            # Submit task to the thread pool
            future_thread = executor.submit(execute_image_download, row['image_url'], file_destination)
            task_map[future_thread] = row['image_url']

        # UI: Visual progress bar for the terminal
        for completed_task in tqdm(as_completed(task_map), total=len(task_map), desc="Downloading"):
            pass

    print("\n--- PRODUCTION DATA EXTRACTION COMPLETE ---")

if __name__ == "__main__":
    run_production_downloader()