import os
import pandas as pd
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from tqdm import tqdm

# ====================
# GLOBAL CONFIGURATION
# ====================
# This is the CSV generated by metadata_sifter.py
PATH_TO_INPUT_EXTRACTION_LIST = "production_image_extraction_list.csv"

# The root directory where folders will be created
BASE_STORAGE_DIRECTORY = "downloaded_plant_images"

# Threading Configuration (Java FixedThreadPool size)
MAX_CONCURRENT_DOWNLOADERS = 25
REQUEST_TIMEOUT_SECONDS = 15

def create_target_directory(species_name: str) -> Path:
    """
    Creates a sanitized folder for each species.
    Replaces spaces with underscores for filesystem compatibility.
    """
    sanitized_folder_name = species_name.replace(" ", "_").replace("/", "-")
    target_path = Path(BASE_STORAGE_DIRECTORY) / sanitized_folder_name
    target_path.mkdir(parents=True, exist_ok=True)
    return target_path

def execute_image_download(url: str, save_path: Path) -> bool:
    """
    Performs the IO operation.
    Includes RESUME LOGIC: skips if the file already exists.
    """
    # RESUME LOGIC: Check disk before hitting network
    if save_path.exists():
        return True

    try:
        # Requesting 'medium' size as Chris requested to save storage
        optimized_url = url.replace("/original/", "/medium/").replace("/large/", "/medium/")

        network_response = requests.get(optimized_url, timeout=REQUEST_TIMEOUT_SECONDS)
        network_response.raise_for_status()

        with open(save_path, 'wb') as local_file:
            local_file.write(network_response.content)
        return True
    except Exception as error:
        # Log failure but keep the thread pool running
        return False

def run_production_downloader():
    """
    The main execution engine.
    Parallel download of ~2 million images.
    """
    if not os.path.exists(PATH_TO_INPUT_EXTRACTION_LIST):
        print(f"CRITICAL ERROR: {PATH_TO_INPUT_EXTRACTION_LIST} not found.")
        return

    # Load the 'Shopping List'
    extraction_df = pd.read_csv(PATH_TO_INPUT_EXTRACTION_LIST)
    print(f"Beginning parallel download for {len(extraction_df)} entries...")


    with ThreadPoolExecutor(max_workers=MAX_CONCURRENT_DOWNLOADERS) as executor:
        task_map = {}

        for index, row in extraction_df.iterrows():
            folder = create_target_directory(row['scientific_name'])
            # Creating a unique filename for the specific entry
            file_destination = folder / f"img_{index}.jpg"

            # Submit task to the thread pool
            future_thread = executor.submit(execute_image_download, row['image_url'], file_destination)
            task_map[future_thread] = row['image_url']

        # UI: Visual progress bar for the terminal
        for completed_task in tqdm(as_completed(task_map), total=len(task_map), desc="Downloading"):
            pass

    print("\n--- PRODUCTION DATA EXTRACTION COMPLETE ---")

if __name__ == "__main__":
    run_production_downloader()